config-version = 2

start-at-login = true
auto-reload-config = true
on-focused-monitor-changed = 'move-mouse monitor-lazy-center'
on-focus-changed = 'move-mouse window-lazy-center'
focus-follows-mouse.enabled = true
gaps.inner.horizontal = 4
gaps.inner.vertical = 4

[mode.main.binding]
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

alt-shift-f = 'layout floating tiling'

alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-left = ['join-with left', 'mode main']
alt-shift-down = ['join-with down', 'mode main']
alt-shift-up = ['join-with up', 'mode main']
alt-shift-right = ['join-with right', 'mode main']
