hl.on("hyprland.start", function()
  hl.exec_cmd("noctalia")
  hl.exec_cmd("hyprctl output create headless STREAM")
  hl.exec_cmd("/bin/sh -c 'sleep 2; systemctl --user start app-dev.lizardbyte.app.Sunshine'")
end)
